version: '3.9'
services:
  v2ray-server:
    container_name: v2ray-server
    restart: always
    image: v2fly/v2fly-core:v5.4.1
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    volumes:
      - "config.json:/etc/v2fly/config.json"
    command: run -c /etc/v2fly/config.json

