v2ray_version: latest
v2ray_dir: /var/v2ray

adguardhome:
  loadconfig: true

# Server config.json vars
inbounds:
  port: 10086
  protocol: vmess
  settings:
    clients: #free from #4
      - id: id 1 in uuid 4 version
      - id: id 2 in uuid 4 version
# Client config.json vars
outbounds:
  protocol: freedom

