- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ docker_dependencies }}"

- name: Add GPG key
  apt_key:
    url: "{{ docker_apt_key }}"
    state: present

- name: Get version codename
  register: codename
  shell: ". /etc/os-release && echo \"$VERSION_CODENAME\""

- name: Add docker registry
  apt_repository:
    repo: "deb {{ docker_repo }} {{ codename.stdout }} stable"
    state: present

- name: Update apt and install docker-ce 
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  loop:
    - "{{ docker_components }}"

- name: Make sure docker is active
  service: 
    name: docker
    state: started
    enabled: yes

- name: Add remote user to "docker" group
  user:
    name: "{{ ansible_user }}"
    groups:
      - docker
    append: yes
