docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl 
  - gnupg-agent
  - software-properties-common
  - python3-pip
  - python3-setuptools

docker_apt_key: https://download.docker.com/linux/debian/gpg
docker_repo: https://download.docker.com/linux/debian

docker_components:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin


